# Generated by Django 4.2.1 on 2023-06-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SampleModelWithAllFields",
            fields=[
                ("big_integer_field", models.BigIntegerField(blank=True)),
                ("binary_field", models.BinaryField(blank=True)),
                ("boolean_field", models.BooleanField(blank=True)),
                ("char_field", models.CharField(blank=True, max_length=255)),
                ("date_field", models.DateField(blank=True)),
                ("datetime_field", models.DateTimeField(blank=True)),
                (
                    "decimal_field",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10),
                ),
                ("duration_field", models.DurationField(blank=True)),
                ("email_field", models.EmailField(blank=True, max_length=254)),
                ("file_field", models.FileField(blank=True, upload_to="files/")),
                ("file_path_field", models.FilePathField(blank=True, path="files/")),
                ("float_field", models.FloatField(blank=True)),
                (
                    "generic_ip_address_field",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                ("image_field", models.ImageField(blank=True, upload_to="images/")),
                ("integer_field", models.IntegerField(blank=True)),
                ("json_field", models.JSONField(blank=True)),
                (
                    "positive_big_integer_field",
                    models.PositiveBigIntegerField(blank=True),
                ),
                ("positive_integer_field", models.PositiveIntegerField(blank=True)),
                (
                    "positive_small_integer_field",
                    models.PositiveSmallIntegerField(blank=True),
                ),
                ("slug_field", models.SlugField(blank=True)),
                (
                    "small_auto_field",
                    models.SmallAutoField(primary_key=True, serialize=False),
                ),
                ("small_integer_field", models.SmallIntegerField(blank=True)),
                ("text_field", models.TextField(blank=True)),
                ("time_field", models.TimeField(blank=True)),
                ("url_field", models.URLField(blank=True)),
                ("uuid_field", models.UUIDField(blank=True)),
            ],
        ),
    ]
