version: 2.1

orbs:
  python: circleci/python@2.1.1
  ansible: trustedshops-public/ansible@2.0.0
  codecov: codecov/codecov@3.2.4

jobs:
  build:
    docker:
      - image: cimg/python:3.11.3

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python manage.py test 
      - store_artifacts:
          path: test-reports
          destination: test-reports

workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
      - build:
          filters:
            branches:
              only: release
        
